name: CI pipeline

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    services:
      postgres:
        image: postgres:13.5-alpine
        env:
          POSTGRES_DB: rent_your_stuff
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk

      - name: Make gradlew executable
        working-directory: ./app
        run: chmod +x ./gradlew

      - name: Run tests
        working-directory: ./app
        env:
          MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rent_your_stuff
          MAIN_DATASOURCE_USERNAME: db_user
          MAIN_DATASOURCE_PASSWORD: db_password
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'